version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: bukukutest
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: admin123
    ports:
      - "3306:3306"
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
